[workspace]
resolver = "2"
members = [
     "scripts/social_token",
     "scripts/tests",
     "scripts/a_token",
     "scripts/payment-channel-type",
     "scripts/cell-owned-lock"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

[profile.dev]
panic = "abort"
